site:
  title: TB Antora docs
  url: https://tbantoradocs.com
  start_page: docs-site::index.adoc
git:
  ensure_git_suffix: false
content:
  branches: master
  sources: 
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/tonybgithub/docs-site
    start_path: docs
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public