site:
  title: TB Antora docs
  url: https://tbantoradocs.com
  start_page: apidocs::index.adoc
git:
  ensure_git_suffix: false
content:
  branches: master
  sources: 
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/tonybgithub/docs-site
    start_path: docs
  - url: https://github.com/TonyBgithub/tb-antoradocs
    branches: [openweather-api, petstore-api]
ui:
  bundle:
    url: https://github.com/TonyBgithub/tb-antoradocs/raw/ui-bundle/build/ui-bundle.zip
output:
  dir: ./public