site:
  title: TB Antora docs
  start_page: apidocs::index.adoc
git:
  ensure_git_suffix: false
content:
  branches: master
  sources: 
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/tonybgithub/docs-site
    start_path: docs
ui: 
  bundle:
    url: https://github.com/TonyBgithub/tb-antoradocs/raw/ui-bundle/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./public
