[build]
publish = "public"
command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull ./antora-playbook.yml"

[build.environment]
NODE_VERSION = "12.18.4"

#[context.production.environment]
#ALGOLIA_API_KEY = "..."
#ALGOLIA_INDEX_NAME = "asciidoctor"
#GOOGLE_ANALYTICS_KEY = "..."

[context.deploy-preview]
command = "node_modules/.bin/antora --html-url-extension-style=indexify --pull --url $DEPLOY_PRIME_URL ./antora-playbook.yml"